import type { Campaign } from "@/lib/content/types";

/**
 * Hero campaigns. Exactly one is active at a time — `activeCampaign` at the
 * bottom of this file decides which. Swapping between them changes the title,
 * copy, media and primary action together, without touching the layout.
 *
 * Photography is from the gallery on davidguetta.com (8 September 2026).
 * REAL CONTENT, NOT CLEARED — see ASSET-MANIFEST.md.
 */

/**
 * Atmospheric loop hero.
 *
 * The video is an ORIGINAL asset generated for this concept by
 * `tools/make-hero-loop.py` — beams, a lighting truss, drifting haze and a
 * crowd line, drawn from scratch. No footage was taken from anywhere: ripping
 * the artist's videos from YouTube would be a far larger rights problem than
 * the stills already flagged in the manifest, and is not something this build
 * does.
 *
 * The poster is frame 0 of that same loop, so the still and the first video
 * frame match exactly and the swap is invisible.
 *
 * Phones keep the photograph. design.md §7B asks for the poster rather than a
 * loop on phones, and a portrait of the artist is the better first impression
 * on a small screen.
 */
export const atmosphericCampaign: Campaign = {
  id: "campaign-atmospheric",
  titleLines: ["David", "Guetta"],
  supportingCopy: "Music. Live. Worldwide.",
  image: {
    src: "/assets/hero/hero-loop-poster.jpg",
    alt: "",
    width: 1920,
    height: 1080,
    focal: { x: 0.5, y: 0.5 },
    source: "Original artwork generated by tools/make-hero-loop.py",
    approval: "approved",
  },
  mobileImage: {
    src: "/assets/hero/hero-mobile.jpg",
    alt: "",
    width: 800,
    height: 1200,
    focal: { x: 0.52, y: 0.18 },
    source: "davidguetta.com/image-gallery (011.jpg)",
    approval: "pending-approval",
  },
  placeholder: "stage",
  video: {
    // Smallest format first: VP9 is roughly half the size of the H.264 build.
    sources: [
      { src: "/assets/hero/hero-loop.webm", type: "video/webm" },
      { src: "/assets/hero/hero-loop.mp4", type: "video/mp4" },
    ],
    poster: "/assets/hero/hero-loop-poster.jpg",
    durationSeconds: 8,
  },
  primaryAction: { label: "View shows", href: "/live" },
  secondaryAction: { label: "Explore music", href: "/music" },
  caption: "Original loop created for this concept — approved stage footage still required",
  approval: "pending-approval",
};

/**
 * Photographic hero — the alternative.
 *
 * The subject sits on the LEFT of this frame with clear space to the right,
 * the mirror of the composition the brief sketched, which is why the hero
 * layout is right-aligned. It keeps the artist's face on desktop, at the cost
 * of the motion. The desktop master is only 1162 px wide and is press
 * portraiture rather than the concert photography the brief asks for.
 */
export const portraitCampaign: Campaign = {
  id: "campaign-portrait",
  titleLines: ["David", "Guetta"],
  supportingCopy: "Music. Live. Worldwide.",
  image: {
    src: "/assets/hero/hero-desktop.jpg",
    alt: "",
    width: 1162,
    height: 1200,
    focal: { x: 0.34, y: 0.12 },
    source: "davidguetta.com/image-gallery (015.jpg)",
    approval: "pending-approval",
  },
  mobileImage: {
    src: "/assets/hero/hero-mobile.jpg",
    alt: "",
    width: 800,
    height: 1200,
    focal: { x: 0.52, y: 0.18 },
    source: "davidguetta.com/image-gallery (011.jpg)",
    approval: "pending-approval",
  },
  placeholder: "stage",
  video: null,
  primaryAction: { label: "View shows", href: "/live" },
  secondaryAction: { label: "Explore music", href: "/music" },
  caption: "Photography from davidguetta.com — not rights-cleared",
  approval: "pending-approval",
};

/** Switch this line to `portraitCampaign` to lead with the photograph instead. */
export const activeCampaign: Campaign = atmosphericCampaign;
