import type { LiveEvent } from "@/lib/content/types";

/**
 * DEMO FIXTURES — not real David Guetta tour dates.
 *
 * Cities, countries and timezones are real geography so region filtering and
 * the venue-local day boundary can be exercised properly. Venue names, event
 * names and ticket links are NOT invented: venues read "Venue to be
 * confirmed" and every ticket URL is null, so each row renders its honest
 * unavailable state. The real provider link lives on siteSettings.
 *
 * The set deliberately covers: every status, a date-only event, a multi-day
 * range, a far-east timezone (Sydney) for the archive boundary, long venue
 * text, and past events for the archive.
 */
export const demoEvents: LiveEvent[] = [
  {
    id: "evt-001",
    title: "Live show",
    venue: "Venue to be confirmed",
    city: "Amsterdam",
    country: "Netherlands",
    countryCode: "NL",
    region: "Europe",
    date: "2026-09-19",
    endDate: null,
    startTime: "22:00",
    timezone: "Europe/Amsterdam",
    status: "tickets-unavailable",
    ticketUrl: null,
    waitlistUrl: null,
    source: "demo-fixture",
    lastVerified: null,
    approval: "demo",
  },
  {
    id: "evt-002",
    title: "Club show",
    venue: "Venue to be confirmed",
    city: "Ibiza",
    country: "Spain",
    countryCode: "ES",
    region: "Europe",
    date: "2026-09-26",
    endDate: null,
    startTime: "23:30",
    timezone: "Europe/Madrid",
    status: "sold-out",
    ticketUrl: null,
    // A waitlist action only appears when a real waitlist URL exists.
    waitlistUrl: null,
    source: "demo-fixture",
    lastVerified: null,
    approval: "demo",
  },
  {
    id: "evt-003",
    title: "Live show",
    venue: "Venue to be confirmed",
    city: "Paris",
    country: "France",
    countryCode: "FR",
    region: "Europe",
    date: "2026-10-03",
    endDate: null,
    startTime: "21:00",
    timezone: "Europe/Paris",
    status: "tickets-unavailable",
    ticketUrl: null,
    waitlistUrl: null,
    source: "demo-fixture",
    lastVerified: null,
    approval: "demo",
  },
  {
    id: "evt-004",
    title: "Live show",
    venue: "Venue to be confirmed",
    city: "London",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    date: "2026-10-17",
    endDate: null,
    startTime: "20:30",
    timezone: "Europe/London",
    status: "postponed",
    ticketUrl: null,
    waitlistUrl: null,
    source: "demo-fixture",
    lastVerified: null,
    approval: "demo",
  },
  {
    id: "evt-005",
    title: "Festival appearance",
    venue: "Festival site — venue and stage to be confirmed",
    city: "Las Vegas",
    country: "United States",
    countryCode: "US",
    region: "North America",
    // Multi-day range, date-only: no start time is invented.
    date: "2026-10-30",
    endDate: "2026-11-01",
    startTime: null,
    timezone: "America/Los_Angeles",
    status: "on-sale-soon",
    ticketUrl: null,
    waitlistUrl: null,
    source: "demo-fixture",
    lastVerified: null,
    approval: "demo",
  },
  {
    id: "evt-006",
    title: "Live show",
    venue: "Venue to be confirmed",
    city: "New York",
    country: "United States",
    countryCode: "US",
    region: "North America",
    date: "2026-11-14",
    endDate: null,
    startTime: "21:30",
    timezone: "America/New_York",
    status: "tickets-unavailable",
    ticketUrl: null,
    waitlistUrl: null,
    source: "demo-fixture",
    lastVerified: null,
    approval: "demo",
  },
  {
    id: "evt-007",
    title: "Live show",
    venue: "Venue to be confirmed",
    city: "Mexico City",
    country: "Mexico",
    countryCode: "MX",
    region: "North America",
    date: "2026-11-28",
    endDate: null,
    startTime: null,
    timezone: "America/Mexico_City",
    status: "cancelled",
    ticketUrl: null,
    waitlistUrl: null,
    source: "demo-fixture",
    lastVerified: null,
    approval: "demo",
  },
  {
    id: "evt-008",
    title: "Festival appearance",
    venue: "Venue to be confirmed",
    city: "São Paulo",
    country: "Brazil",
    countryCode: "BR",
    region: "South America",
    date: "2026-12-12",
    endDate: null,
    startTime: null,
    timezone: "America/Sao_Paulo",
    status: "on-sale-soon",
    ticketUrl: null,
    waitlistUrl: null,
    source: "demo-fixture",
    lastVerified: null,
    approval: "demo",
  },
  {
    id: "evt-009",
    title: "Live show",
    venue: "Venue to be confirmed",
    city: "Dubai",
    country: "United Arab Emirates",
    countryCode: "AE",
    region: "Middle East",
    date: "2027-01-16",
    endDate: null,
    startTime: "22:00",
    timezone: "Asia/Dubai",
    status: "tickets-unavailable",
    ticketUrl: null,
    waitlistUrl: null,
    source: "demo-fixture",
    lastVerified: null,
    approval: "demo",
  },
  {
    id: "evt-010",
    title: "Live show",
    venue: "Venue to be confirmed",
    city: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    region: "Asia",
    date: "2027-02-06",
    endDate: null,
    startTime: "21:00",
    timezone: "Asia/Tokyo",
    status: "tickets-unavailable",
    ticketUrl: null,
    waitlistUrl: null,
    source: "demo-fixture",
    lastVerified: null,
    approval: "demo",
  },
  {
    id: "evt-011",
    title: "Live show",
    venue: "Venue to be confirmed",
    city: "Sydney",
    country: "Australia",
    countryCode: "AU",
    region: "Oceania",
    date: "2027-02-20",
    endDate: null,
    startTime: null,
    timezone: "Australia/Sydney",
    status: "tickets-unavailable",
    ticketUrl: null,
    waitlistUrl: null,
    source: "demo-fixture",
    lastVerified: null,
    approval: "demo",
  },
  {
    id: "evt-012",
    title: "Festival appearance",
    venue: "Venue to be confirmed",
    city: "Cape Town",
    country: "South Africa",
    countryCode: "ZA",
    region: "Africa",
    date: "2027-03-13",
    endDate: null,
    startTime: null,
    timezone: "Africa/Johannesburg",
    status: "tickets-unavailable",
    ticketUrl: null,
    waitlistUrl: null,
    source: "demo-fixture",
    lastVerified: null,
    approval: "demo",
  },
  {
    id: "evt-013",
    title: "Live show",
    venue: "Venue to be confirmed",
    city: "Berlin",
    country: "Germany",
    countryCode: "DE",
    region: "Europe",
    date: "2027-04-10",
    endDate: null,
    startTime: "23:00",
    timezone: "Europe/Berlin",
    status: "tickets-unavailable",
    ticketUrl: null,
    waitlistUrl: null,
    source: "demo-fixture",
    lastVerified: null,
    approval: "demo",
  },
  {
    id: "evt-014",
    title: "Live show",
    venue: "Venue to be confirmed",
    city: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    region: "Europe",
    date: "2026-08-15",
    endDate: null,
    startTime: "23:00",
    timezone: "Europe/Madrid",
    status: "tickets-unavailable",
    ticketUrl: null,
    waitlistUrl: null,
    source: "demo-fixture",
    lastVerified: null,
    approval: "demo",
  },
  {
    id: "evt-015",
    title: "Festival appearance",
    venue: "Venue to be confirmed",
    city: "Miami",
    country: "United States",
    countryCode: "US",
    region: "North America",
    date: "2026-07-04",
    endDate: null,
    startTime: null,
    timezone: "America/New_York",
    status: "tickets-unavailable",
    ticketUrl: null,
    waitlistUrl: null,
    source: "demo-fixture",
    lastVerified: null,
    approval: "demo",
  },
];
