import type { Release } from "@/lib/content/types";

/**
 * DEMO FIXTURES — not real David Guetta releases.
 *
 * Titles are deliberately generic placeholders. No real release name, credit,
 * tracklist or streaming link is invented here. They exist so the layout can
 * be judged against realistic title lengths and catalogue sizes.
 * Replace wholesale before launch; see docs/CONTENT-GUIDE.md.
 */
export const demoReleases: Release[] = [
  {
    id: "rel-001",
    slug: "sample-release-one",
    title: "Sample Release One",
    artists: ["David Guetta", "Featured Artist A"],
    type: "single",
    releaseDate: "2026-08-21",
    artwork: null,
    placeholder: "artwork",
    description:
      "Placeholder description. Replace with the approved campaign copy for the release being featured — two or three lines is the intended length.",
    smartLink: null,
    platforms: [],
    tracklist: null,
    credits: null,
    featured: true,
    approval: "demo",
  },
  {
    id: "rel-002",
    slug: "sample-release-two-extended-mix",
    title: "Sample Release Two (Extended Mix)",
    artists: ["David Guetta"],
    type: "remix",
    releaseDate: "2026-06-12",
    artwork: null,
    placeholder: "artwork",
    description: "Placeholder description for a remix entry.",
    smartLink: null,
    platforms: [],
    tracklist: null,
    credits: null,
    featured: false,
    approval: "demo",
  },
  {
    id: "rel-003",
    slug: "sample-collaboration-with-a-deliberately-long-placeholder-title",
    title: "Sample Collaboration With A Deliberately Long Placeholder Title",
    artists: ["David Guetta", "Featured Artist B", "Featured Artist C"],
    type: "single",
    releaseDate: "2026-03-27",
    artwork: null,
    placeholder: "artwork",
    // Deliberately long: this entry is the wrapping test for cards, the
    // detail page H1 and the accessible names on listen controls.
    description:
      "Placeholder description. This entry exists to test long titles, multiple credited artists and text wrapping at 360 px.",
    smartLink: null,
    platforms: [],
    tracklist: null,
    credits: null,
    featured: false,
    approval: "demo",
  },
  {
    id: "rel-004",
    slug: "sample-album",
    title: "Sample Album",
    artists: ["David Guetta"],
    type: "album",
    releaseDate: "2025-11-07",
    artwork: null,
    placeholder: "artwork",
    description: "Placeholder description for an album entry with a tracklist.",
    smartLink: null,
    platforms: [],
    tracklist: [
      "Placeholder track one",
      "Placeholder track two",
      "Placeholder track three",
      "Placeholder track four",
      "Placeholder track five",
    ],
    credits: "Credits supplied by the client's team. Placeholder text only.",
    featured: false,
    approval: "demo",
  },
  {
    id: "rel-005",
    slug: "sample-ep",
    title: "Sample EP",
    artists: ["David Guetta", "Featured Artist D"],
    type: "ep",
    releaseDate: "2025-05-16",
    artwork: null,
    placeholder: "artwork",
    description: "Placeholder description for an EP entry.",
    smartLink: null,
    platforms: [],
    tracklist: null,
    credits: null,
    featured: false,
    approval: "demo",
  },
  {
    id: "rel-006",
    slug: "sample-compilation",
    title: "Sample Compilation",
    artists: ["David Guetta"],
    type: "compilation",
    releaseDate: "2024-09-20",
    artwork: null,
    placeholder: "artwork",
    description: "Placeholder description for a compilation entry.",
    smartLink: null,
    platforms: [],
    tracklist: null,
    credits: null,
    featured: false,
    approval: "demo",
  },
];
