import type { Video } from "@/lib/content/types";

/**
 * Videos from the official David Guetta YouTube channel, reached through the
 * playlist that davidguetta.com links to as "Videos". Every title, channel and
 * thumbnail below was confirmed one at a time through YouTube's oEmbed
 * endpoint on 8 September 2026 — none of it is guesswork, and anything the
 * endpoint did not attribute to the "David Guetta" channel was dropped.
 *
 * REAL CONTENT, NOT CLEARED. Stills are the official YouTube thumbnails, used
 * here as concept placeholders. An approved video selection and approved
 * stills are still required — see ASSET-MANIFEST.md.
 *
 * `date` and `duration` are null because the source does not state them.
 * `category` comes from the wording in each official title. Every video in the
 * linked playlist is a music video, so the category filter on /watch stays
 * hidden until a second category (live sets, visualizers) is supplied.
 */
export const officialVideos: Video[] = [
  {
    id: "vid-001",
    slug: "sorana-and-david-guetta-redrum-official-video",
    title: "Sorana & David Guetta - redruM (Official Video)",
    providerUrl: "https://www.youtube.com/watch?v=v8TVixpaBcQ",
    embedId: "v8TVixpaBcQ",
    provider: "youtube",
    still: {
      src: "/assets/video/v8TVixpaBcQ.jpg",
      alt: "Sorana & David Guetta - redruM (Official Video) — video still",
      width: 1280,
      height: 720,
      source: "i.ytimg.com (official YouTube thumbnail)",
      approval: "pending-approval",
    },
    placeholder: "stage",
    // Derived from the wording the official title itself uses, not assigned.
    category: "Music video",
    date: null,
    duration: null,
    featured: true,
    approval: "pending-approval",
  },
  {
    id: "vid-002",
    slug: "david-guetta-teddy-swims-tones-and-i-gone-gone-gone-official-music-vid",
    title: "David Guetta, Teddy Swims, Tones and I - Gone Gone Gone [Official Music Video]",
    providerUrl: "https://www.youtube.com/watch?v=8iT9DRe3cHE",
    embedId: "8iT9DRe3cHE",
    provider: "youtube",
    still: {
      src: "/assets/video/8iT9DRe3cHE.jpg",
      alt: "David Guetta, Teddy Swims, Tones and I - Gone Gone Gone [Official Music Video] — video still",
      width: 1280,
      height: 720,
      source: "i.ytimg.com (official YouTube thumbnail)",
      approval: "pending-approval",
    },
    placeholder: "stage",
    // Derived from the wording the official title itself uses, not assigned.
    category: "Music video",
    date: null,
    duration: null,
    featured: false,
    approval: "pending-approval",
  },
  {
    id: "vid-003",
    slug: "david-guetta-and-cedric-gervais-a-better-world-official-video",
    title: "David Guetta & Cedric Gervais - A Better World (Official Video)",
    providerUrl: "https://www.youtube.com/watch?v=RRCuysV9Z18",
    embedId: "RRCuysV9Z18",
    provider: "youtube",
    still: {
      src: "/assets/video/RRCuysV9Z18.jpg",
      alt: "David Guetta & Cedric Gervais - A Better World (Official Video) — video still",
      width: 1280,
      height: 720,
      source: "i.ytimg.com (official YouTube thumbnail)",
      approval: "pending-approval",
    },
    placeholder: "stage",
    // Derived from the wording the official title itself uses, not assigned.
    category: "Music video",
    date: null,
    duration: null,
    featured: false,
    approval: "pending-approval",
  },
  {
    id: "vid-004",
    slug: "david-guetta-and-willy-william-and-nicky-jam-cuentale-official-video",
    title: "David Guetta & Willy William & Nicky Jam - Cuentale (Official Video)",
    providerUrl: "https://www.youtube.com/watch?v=JXzHn1CFRvE",
    embedId: "JXzHn1CFRvE",
    provider: "youtube",
    still: {
      src: "/assets/video/JXzHn1CFRvE.jpg",
      alt: "David Guetta & Willy William & Nicky Jam - Cuentale (Official Video) — video still",
      width: 1280,
      height: 720,
      source: "i.ytimg.com (official YouTube thumbnail)",
      approval: "pending-approval",
    },
    placeholder: "stage",
    // Derived from the wording the official title itself uses, not assigned.
    category: "Music video",
    date: null,
    duration: null,
    featured: false,
    approval: "pending-approval",
  },
  {
    id: "vid-005",
    slug: "david-guetta-and-sia-beautiful-people-official-video",
    title: "David Guetta & Sia - Beautiful People (Official Video)",
    providerUrl: "https://www.youtube.com/watch?v=S2fSojJqyNY",
    embedId: "S2fSojJqyNY",
    provider: "youtube",
    still: {
      src: "/assets/video/S2fSojJqyNY.jpg",
      alt: "David Guetta & Sia - Beautiful People (Official Video) — video still",
      width: 1280,
      height: 720,
      source: "i.ytimg.com (official YouTube thumbnail)",
      approval: "pending-approval",
    },
    placeholder: "stage",
    // Derived from the wording the official title itself uses, not assigned.
    category: "Music video",
    date: null,
    duration: null,
    featured: false,
    approval: "pending-approval",
  },
  {
    id: "vid-006",
    slug: "david-guetta-alphaville-and-ava-max-forever-young-official-music-video",
    title: "David Guetta, Alphaville & Ava Max - Forever Young (Official Music Video)",
    providerUrl: "https://www.youtube.com/watch?v=_AfmgOpoCHI",
    embedId: "_AfmgOpoCHI",
    provider: "youtube",
    still: {
      src: "/assets/video/_AfmgOpoCHI.jpg",
      alt: "David Guetta, Alphaville & Ava Max - Forever Young (Official Music Video) — video still",
      width: 1280,
      height: 720,
      source: "i.ytimg.com (official YouTube thumbnail)",
      approval: "pending-approval",
    },
    placeholder: "stage",
    // Derived from the wording the official title itself uses, not assigned.
    category: "Music video",
    date: null,
    duration: null,
    featured: false,
    approval: "pending-approval",
  },
  {
    id: "vid-007",
    slug: "david-guetta-and-onerepublic-i-don-t-wanna-wait-official-video",
    title: "David Guetta & OneRepublic - I Don't Wanna Wait (Official Video)",
    providerUrl: "https://www.youtube.com/watch?v=dSDbwfXX5_I",
    embedId: "dSDbwfXX5_I",
    provider: "youtube",
    still: {
      src: "/assets/video/dSDbwfXX5_I.jpg",
      alt: "David Guetta & OneRepublic - I Don't Wanna Wait (Official Video) — video still",
      width: 1280,
      height: 720,
      source: "i.ytimg.com (official YouTube thumbnail)",
      approval: "pending-approval",
    },
    placeholder: "stage",
    // Derived from the wording the official title itself uses, not assigned.
    category: "Music video",
    date: null,
    duration: null,
    featured: false,
    approval: "pending-approval",
  },
  {
    id: "vid-008",
    slug: "david-guetta-and-kim-petras-when-we-were-young-the-logical-song-offici",
    title: "David Guetta & Kim Petras - When We Were Young (The Logical Song) [Official Video]",
    providerUrl: "https://www.youtube.com/watch?v=YBGtzfK5Bak",
    embedId: "YBGtzfK5Bak",
    provider: "youtube",
    still: {
      src: "/assets/video/YBGtzfK5Bak.jpg",
      alt: "David Guetta & Kim Petras - When We Were Young (The Logical Song) [Official Video] — video still",
      width: 1280,
      height: 720,
      source: "i.ytimg.com (official YouTube thumbnail)",
      approval: "pending-approval",
    },
    placeholder: "stage",
    // Derived from the wording the official title itself uses, not assigned.
    category: "Music video",
    date: null,
    duration: null,
    featured: false,
    approval: "pending-approval",
  },
  {
    id: "vid-009",
    slug: "david-guetta-ayra-starr-and-lil-durk-big-fu-official-video",
    title: "David Guetta, Ayra Starr & Lil Durk - Big FU (Official Video)",
    providerUrl: "https://www.youtube.com/watch?v=6xk-H3ogcKQ",
    embedId: "6xk-H3ogcKQ",
    provider: "youtube",
    still: {
      src: "/assets/video/6xk-H3ogcKQ.jpg",
      alt: "David Guetta, Ayra Starr & Lil Durk - Big FU (Official Video) — video still",
      width: 1280,
      height: 720,
      source: "i.ytimg.com (official YouTube thumbnail)",
      approval: "pending-approval",
    },
    placeholder: "stage",
    // Derived from the wording the official title itself uses, not assigned.
    category: "Music video",
    date: null,
    duration: null,
    featured: false,
    approval: "pending-approval",
  },
  {
    id: "vid-010",
    slug: "david-guetta-anne-marie-coi-leray-baby-dont-hurt-me-official-video",
    title: "David Guetta, Anne-Marie, Coi Leray - Baby Don’t Hurt Me (Official Video)",
    providerUrl: "https://www.youtube.com/watch?v=k3DBmAlUh1A",
    embedId: "k3DBmAlUh1A",
    provider: "youtube",
    still: {
      src: "/assets/video/k3DBmAlUh1A.jpg",
      alt: "David Guetta, Anne-Marie, Coi Leray - Baby Don’t Hurt Me (Official Video) — video still",
      width: 1280,
      height: 720,
      source: "i.ytimg.com (official YouTube thumbnail)",
      approval: "pending-approval",
    },
    placeholder: "stage",
    // Derived from the wording the official title itself uses, not assigned.
    category: "Music video",
    date: null,
    duration: null,
    featured: false,
    approval: "pending-approval",
  },
  {
    id: "vid-011",
    slug: "david-guetta-and-bebe-rexha-i-m-good-blue-official-music-video",
    title: "David Guetta & Bebe Rexha - I'm Good (Blue) [Official Music Video]",
    providerUrl: "https://www.youtube.com/watch?v=90RLzVUuXe4",
    embedId: "90RLzVUuXe4",
    provider: "youtube",
    still: {
      src: "/assets/video/90RLzVUuXe4.jpg",
      alt: "David Guetta & Bebe Rexha - I'm Good (Blue) [Official Music Video] — video still",
      width: 1280,
      height: 720,
      source: "i.ytimg.com (official YouTube thumbnail)",
      approval: "pending-approval",
    },
    placeholder: "stage",
    // Derived from the wording the official title itself uses, not assigned.
    category: "Music video",
    date: null,
    duration: null,
    featured: false,
    approval: "pending-approval",
  },
  {
    id: "vid-012",
    slug: "david-guetta-vs-benny-benassi-satisfaction-official-video",
    title: "David Guetta vs Benny Benassi - Satisfaction (Official Video)",
    providerUrl: "https://www.youtube.com/watch?v=0-_bCbCc6lY",
    embedId: "0-_bCbCc6lY",
    provider: "youtube",
    still: {
      src: "/assets/video/0-_bCbCc6lY.jpg",
      alt: "David Guetta vs Benny Benassi - Satisfaction (Official Video) — video still",
      width: 1280,
      height: 720,
      source: "i.ytimg.com (official YouTube thumbnail)",
      approval: "pending-approval",
    },
    placeholder: "stage",
    // Derived from the wording the official title itself uses, not assigned.
    category: "Music video",
    date: null,
    duration: null,
    featured: false,
    approval: "pending-approval",
  },
  {
    id: "vid-013",
    slug: "david-guetta-and-becky-hill-and-ella-henderson-crazy-what-love-can-do",
    title: "David Guetta & Becky Hill & Ella Henderson - Crazy What Love Can Do (Official Music Video)",
    providerUrl: "https://www.youtube.com/watch?v=8bzesUu_a4I",
    embedId: "8bzesUu_a4I",
    provider: "youtube",
    still: {
      src: "/assets/video/8bzesUu_a4I.jpg",
      alt: "David Guetta & Becky Hill & Ella Henderson - Crazy What Love Can Do (Official Music Video) — video still",
      width: 1280,
      height: 720,
      source: "i.ytimg.com (official YouTube thumbnail)",
      approval: "pending-approval",
    },
    placeholder: "stage",
    // Derived from the wording the official title itself uses, not assigned.
    category: "Music video",
    date: null,
    duration: null,
    featured: false,
    approval: "pending-approval",
  },
];
